---
greeting:       hello world!
mastermsg:      The master message
more_stuff:
    foo:        10
    bar:        The bar value
    baz:
      wibble:   pleasantly
      frusset:  pouch

components:
    - database 
    - frusset
    - middleware
resources:
     - workspaces
#    - forms
#    - apps
#    - entities
#    - projects
#    - sites

schemas: 
  urls:
    tree_type: uri
