---
greeting:       hello world!
mastermsg:      The master message
more_stuff:
    foo:        10
    bar:        The bar value
    baz:
      wibble:   pleasantly
      frusset:  pouch

# schemas for data items and components
items:
  urls:
    tree_type:  uri

  test_one:
    component:  test
    singleton:  1

# no longer used
#components:
#    - database 
#    - frusset
#    - middleware

resources:
     - workspaces
#    - forms
#    - apps
#    - entities
#    - projects
#    - sites

