---
greeting:       hello world!
mastermsg:      The master message    
components:     
    - database 
    - entities 
    - frusset
resources:
    - forms
    - apps
    - entities
    - projects
projects:
    cache_instances:    1

