---
greeting:       hello world!
mastermsg:      The master message    
components:     
    - database 
    - entities 
    - frusset
    - middleware
resources:
    - forms
    - apps
    - entities
    - projects
    - sites
