---
greeting:       hello world!
mastermsg:      The master message
more_stuff:
    foo:        10
    bar:        The bar value
    baz:
      wibble:   pleasantly
      frusset:  pouch

components:
    - database 
    - entities 
    - frusset
    - middleware
resources:
    - forms
    - apps
    - entities
    - projects
    - sites
