-
  name:   Andy Wardley
  email:  abw@wardley.org
  role:   System Architect
  skills: Database abstraction, Web applications, Templates, HTML, Javascript, CSS
-
  name:   Ford Prefect
  email:  ford@horse_and_groom.guildford.org

