#-----------------------------------------------------------------------------
# This is a wildcard entry for "accept: *" headers
#-----------------------------------------------------------------------------

any:
    accept:
                - '*'
                - '*/*'
                - '*.*'


#-----------------------------------------------------------------------------
# The main content types that we generate from templates or server statically
#-----------------------------------------------------------------------------

html:
    content_type: text/html
    charset:      utf-8

css:
    content_type: text/css
    charset:      utf-8

js:
    content_type: text/javascript
    charset:      utf-8

json:
    content_type: application/json
    charset:      utf-8
    accept:
                - text/json
                - text/x-json

xml:
    content_type: application/xml
    charset:      utf-8
    wrapper:      xml
    accept:
                - text/xml


