name:           The Golf Project

components:     routes

delegates:
  router:       routes
  add_route:    routes
  match:        routes
  match_route:  routes.match

routes:
  foo:
    title:      The Foo Page

  bar/*:
    title:      The Bar Page
    section:    The Bar Section

  bar/baz:
    title:      The Baz Page

  00 /country/<int:id>:
    title:      Country by ID

  01 /country/<text:code>:
    title:      Country by Code

